apiVersion: v1
kind: Service
metadata:
  name: waf
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    service: waf
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: waf
  selector:
    service: waf
  loadBalancerIP: 10.164.0.14
  type: LoadBalancer
